package com.anvipus.core.utils

class Constants {
    companion object {
        const val KEY_CARD = "CARD"
        const val KEY_EXTRA = "EXTRA"
        const val KEY_EMONEY = "EMONEY"
        const val KEY_NONE = "NONE"
        const val KEY_TEXT_PLAINT = "text/plain"
        const val KEY_INITIAL_PARAMS_MERCHANT_LABEL = "merchant_label"
        const val KEY_INITIAL_PARAMS_TOKEN = "token"
        const val KEY_INITIAL_PARAMS_DLK_CODE = "dlk_code"
        const val KEY_INITIAL_PARAMS_PHONE_ID = "phone_id"
        const val KEY_INITIAL_PARAMS_FK_USER_ID = "fk_user_id"
        const val KEY_INITIAL_PARAMS_FK_WALLET_ID = "fk_wallet_id"
        const val KEY_INITIAL_PARAMS_VERSION_CODE = "application_version_code"
        const val KEY_INITIAL_PARAMS_VERSION_NAME = "application_version_name"
        const val KEY_INITIAL_PARAMS_OS_TYPE = "device_os"
        const val KEY_INITIAL_PARAMS_SDK_VERSION = "sdk_version"
        const val KEY_AOS = "android"
        const val KEY_INITIAL_PARAMS_FINGERPRINT = "device_identification"
        const val KEY_INITIAL_PARAMS_DEVICE_ID = "device_id"
        const val KEY_INITIAL_PARAMS_USER_AGENT = "user_agent"
        const val KEY_INITIAL_PARAMS_PUBLIC_IP_ADDRESS = "public_ip_address"
        const val KEY_INITIAL_PARAMS_LOCATION = "location"
        const val KEY_INITIAL_PARAMS_MANUFACTURE = "manufacture"
        const val KEY_INITIAL_PARAMS_MODEL = "model"
        const val KEY_INITIAL_PARAMS_BRAND = "brand"
        const val KEY_WEBVIEW = "webview"
        const val KEY_QRIS_CHECK_STATUS = "qris_check_status"
        const val KEY_TIMESTAMP = "timestamp"
        const val KEY_TIMEZONE = "timezone"
        const val FORMAT_DATE_V1 = "yyyy-MM-dd HH:mm:ss"
        const val FORMAT_DATE_V2 = "dd-MMM-yyyy"
        const val FORMAT_DATE_V3 = "dd MMM yyyy, HH:mm:ss"
        const val KEY_IS_REFRESHED_HOME = "is_refreshed_home"
        const val KEY_LAST_IP_ADDRESS = "last_ip_address"
        const val KEY_USER_NOT_FOUND = "USER_NOT_FOUND"
        const val KEY_PREFIX_CODE_NOT_EXIST = "PREFIX_CODE_NOT_EXIST"
        const val KEY_BILLER_TIMEOUT = "BILLER_TIMEOUT"
        const val KEY_PAY_PENDING = "PAY_PENDING"
        const val KEY_BILLER_POSTPAID = "biller_postpaid"
        const val KEY_BILLER_PREPAID = "biller_prepaid"
        const val KEY_BILLER = "biller"
        const val KEY_DEEPLINK_PAYMENT = "deeplink_payment"
        const val KEY_AUTH_ID_EXPIRED = "AUTH_ID_EXPIRED"
        const val KEY_AUTH_ID_NOT_FOUND = "AUTH_ID_NOT_FOUND"
        const val KEY_PIN_AUTH_NOT_VALID = "PIN_AUTH_NOT_VALID"
        const val KEY_PUSH_TO_PAY = "push_to_pay"
        const val KEY_PUSH_TO_PAY_HOME = "push_to_pay_home"
        const val KEY_PUSH_TO_PAY_NOTIF = "push_to_pay_notif"

        const val EXTRA_IMAGE_URI = "EXTRA_IMAGE_URI"
        const val EXTRA_LIST_IMAGE_URI = "EXTRA_LIST_IMAGE_URI"
        const val EXTRA_IMAGE_URI_2 = "EXTRA_IMAGE_URI_2"
        const val EXTRA_IMAGE_URI_3 = "EXTRA_IMAGE_URI_3"
        const val EXTRA_KTP = "EXTRA_KTP"
        const val EXTRA_WITH_FLASH = "EXTRA_WITH_FLASH"
        const val EXTRA_CAMERA_ONLY = "EXTRA_CAMERA_ONLY"
        const val EXTRA_ERROR_MESSAGE = "EXTRA_ERROR_MESSAGE"
        const val EXTRA_RESULT = "EXTRA_RESULT"
        const val CAPTURE_EKTP_REQUEST_CODE = 102
        const val ERROR_MSG_IMAGE_PROCESS_DEFAULT = "Terjadi kesalahan pada saat memproses gambar"

    }
}